# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, help_text='Введите фамилию', max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Введите отчество', max_length=30, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], help_text='Выберите пол', max_length=7, verbose_name='Пол')),
                ('dob', models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название должности', max_length=50, unique=True, verbose_name='Должность')),
                ('category', models.CharField(choices=[('Специалист', 'Специалист'), ('Служащий', 'Служащий'), ('Рабочий', 'Рабочий')], help_text='Выберите категорию', max_length=10, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Выберите должность', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jobs.Position', verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('first_name', 'last_name', 'patronymic', 'dob')]),
        ),
    ]
