# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(help_text='Введите дату рождения в формате: dd.mm.YYYY', verbose_name='Дата рождения'),
        ),
    ]
