# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название должности', max_length=20, unique=True, verbose_name='Должность'),
        ),
    ]
