# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-09 12:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=18, help_text='Введите возраст', validators=[django.core.validators.MaxValueValidator(150, 'Слишком большой возраст!'), django.core.validators.MinValueValidator(14, 'Слишком маленький возраст')], verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
