# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.CharField(choices=[('Специалист', 'Специалист'), ('Служащий', 'Служащий'), ('Рабочий', 'Рабочий')], help_text='Выберите категорию', max_length=10, verbose_name='Категория'),
        ),
    ]
