# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220609_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Выберите должность', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jobs.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Введите название должности', max_length=50, verbose_name='Должность'),
        ),
    ]
