# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220609_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Введите фамилию', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название должности', max_length=50, unique=True, verbose_name='Должность'),
        ),
    ]
