# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-06-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20220609_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], help_text='Выберите пол', max_length=7, verbose_name='Пол'),
        ),
    ]
